function(vcpkg_fix_packages)
    file(GLOB_RECURSE _debug_confs
        ${CURRENT_PACKAGES_DIR}/*debug.cmake)
    foreach(_file ${_debug_confs})
        message(STATUS "Fixing cmake package ${_file}")
        file(READ ${_file} _content)
        string(REPLACE "\${_IMPORT_PREFIX}" "\${_IMPORT_PREFIX}/debug" _content "${_content}")
        string(REPLACE "debug/tools" "tools" _content "${_content}")
        string(REGEX REPLACE [=["\${_IMPORT_PREFIX}/debug/bin/([a-zA-Z0-9_]+\.exe)"]=] [=["${_IMPORT_PREFIX}/tools/\1"]=] _content "${_content}")
        file(WRITE ${_file} "${_content}")
    endforeach()
    file(GLOB_RECURSE _release_confs
        ${CURRENT_PACKAGES_DIR}/*release.cmake)
    foreach(_file ${_release_confs})
        message(STATUS "Fixing cmake package ${_file}")
        file(READ ${_file} _content)
        string(REGEX REPLACE [=["\${_IMPORT_PREFIX}/bin/([a-zA-Z0-9_]+\.exe)"]=] [=["${_IMPORT_PREFIX}/tools/\1"]=] _content "${_content}")
        file(WRITE ${_file} "${_content}")
    endforeach()
endfunction()